apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.configmap.name}}
  namespace: {{.Values.namespace.name}}
data:
  index.html: |
    <html>
    <head>
      <title>Sample Page</title>
    </head>
    <body>
      <h1>Hello, World!</h1>
      <p>This is a simple HTML page served from a ConfigMap.</p>
    </body>
    </html>